### ISSUE TITLE
Image @hub.docker.com

### ISSUE THREAD

**Issue by smnbbrv** [juanjoDiaz/grpc-web-generator#2]
Hi guys,

could you please configure the image to be available at official docker repo?

**Comment by juanjoDiaz** [comment]
Hi @smnbbrv ,

Can you clarify what you mean?

The image is available at https://hub.docker.com/r/juanjodiaz/grpc-web-generator/ so you can use it freely.

Would you like it to become an actual official repo?
I'm sure if that would even be possible since I don't belong to the gRPC team.
Also, I think that the gRPC should eventually create an npm package to replace this image.

**Comment by smnbbrv** [comment]
No, no :) It's just about the fact that I didn't find it on a README.md before. Now it's there, thanks a lot!
